package com.dzkandian.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dzkandian.storage.bean.video.VideoRecordBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECORD_VIDEO".
*/
public class VideoRecordBeanDao extends AbstractDao<VideoRecordBean, Long> {

    public static final String TABLENAME = "RECORD_VIDEO";

    /**
     * Properties of entity VideoRecordBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VId = new Property(1, String.class, "vId", false, "V_ID");
        public final static Property VType = new Property(2, String.class, "vType", false, "V_TYPE");
        public final static Property VScale = new Property(3, Integer.class, "vScale", false, "V_SCALE");
    }


    public VideoRecordBeanDao(DaoConfig config) {
        super(config);
    }
    
    public VideoRecordBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECORD_VIDEO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"V_ID\" TEXT," + // 1: vId
                "\"V_TYPE\" TEXT," + // 2: vType
                "\"V_SCALE\" INTEGER);"); // 3: vScale
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECORD_VIDEO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VideoRecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String vId = entity.getVId();
        if (vId != null) {
            stmt.bindString(2, vId);
        }
 
        String vType = entity.getVType();
        if (vType != null) {
            stmt.bindString(3, vType);
        }
 
        Integer vScale = entity.getVScale();
        if (vScale != null) {
            stmt.bindLong(4, vScale);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VideoRecordBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String vId = entity.getVId();
        if (vId != null) {
            stmt.bindString(2, vId);
        }
 
        String vType = entity.getVType();
        if (vType != null) {
            stmt.bindString(3, vType);
        }
 
        Integer vScale = entity.getVScale();
        if (vScale != null) {
            stmt.bindLong(4, vScale);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VideoRecordBean readEntity(Cursor cursor, int offset) {
        VideoRecordBean entity = new VideoRecordBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // vId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // vType
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // vScale
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VideoRecordBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVScale(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VideoRecordBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VideoRecordBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VideoRecordBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
